version: "3"

services:
  node_backend:
    build: ./backend
    container_name: node_backend
    restart: always
    volumes:
      - ./backend:/digital-bank
    depends_on:
      - mysql_db
    ports:
      - 3001:3001
    environment:
      MYSQL_HOST: 'mysql_db'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: '123456'
      MYSQL_DATABASE: 'db'

  mysql_db:
    image: mysql:8.0.21
    container_name: "mysql_db"
    platform: linux/x86_64
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: '123456'
    restart: 'always'